"""Make scalp research timestamps timezone-aware on existing databases."""
from alembic import op
import sqlalchemy as sa

revision = "0060_scalp_research_tz"
down_revision = "0059_scalp_research"
branch_labels = None
depends_on = None


def upgrade():
    # Existing naive values were generated by the application as UTC. Preserve
    # their instant while making the PostgreSQL columns explicit timestamptz.
    if op.get_bind().dialect.name == "postgresql":
        for column in ("started_at", "completed_at", "created_at"):
            op.execute(
                sa.text(
                    f"ALTER TABLE scalp_research_runs "
                    f"ALTER COLUMN {column} TYPE TIMESTAMP WITH TIME ZONE "
                    f"USING {column} AT TIME ZONE 'UTC'"
                )
            )


def downgrade():
    raise RuntimeError("0060 is forward-only; restore a verified backup to roll back")
