from __future__ import annotations

from app.models.crypto_data import CryptoCandle, CollectionRun
from app.models import shadow, execution, stock_paper  # Register priority-package tables with Base.

from app.models.models import (
    Asset,
    AuditLog,
    CandidateDecisionJournal,
    EconomicIndicator,
    MarketPrice,
    IntradayBar,
    CorporateAction,
    MarketRegime,
    ModelPrediction,
    ModelValidationFold,
    NewsArticle,
    Notification,
    PaperTrade,
    RiskRule,
    ResearchModelRun,
    StockDatasetSnapshot,
    StockHoldoutConsumption,
    StockHoldoutReservation,
    StockModelRegistry,
    StockPaperModelBinding,
    StockPaperTrial,
    StockPaperTrialDecision,
    StockPaperTrialMetric,
    StockTrainingJob,
    ScannerRefreshJob,
    Strategy,
    StrategyBacktest,
    StrategyExperiment,
    StrategyMemory,
    StrategySignal,
    TradeCandidateSnapshot,
)
from app.models.stock_paper import (
    StockPaperAccount,
    StockPaperBrokerActivity,
    StockPaperEquitySnapshot,
    StockPaperFill,
    StockPaperLedgerEvent,
    StockPaperOrder,
    StockPaperPosition,
    StockPaperStrategyEvidence,
    StockPaperTrialLot,
)

__all__ = [
    "Asset",
    "AuditLog",
    "CandidateDecisionJournal",
    "EconomicIndicator",
    "MarketPrice",
    "IntradayBar",
    "CorporateAction",
    "MarketRegime",
    "ModelPrediction",
    "ModelValidationFold",
    "NewsArticle",
    "Notification",
    "PaperTrade",
    "RiskRule",
    "ResearchModelRun",
    "StockDatasetSnapshot",
    "StockHoldoutConsumption",
    "StockHoldoutReservation",
    "StockModelRegistry",
    "StockPaperModelBinding",
    "StockPaperTrial",
    "StockPaperTrialDecision",
    "StockPaperTrialMetric",
    "StockTrainingJob",
    "ScannerRefreshJob",
    "Strategy",
    "StrategyBacktest",
    "StrategyExperiment",
    "StrategyMemory",
    "StrategySignal",
    "TradeCandidateSnapshot",
    "StockPaperAccount",
    "StockPaperBrokerActivity",
    "StockPaperEquitySnapshot",
    "StockPaperFill",
    "StockPaperLedgerEvent",
    "StockPaperOrder",
    "StockPaperPosition",
    "StockPaperStrategyEvidence",
]
